### ISSUE TITLE
CKCC PNOC_RNA-seq.20160114

### ISSUE THREAD

**Issue by Jeltje** [BD2KGenomics/core-operations#10]
Uploading to S3

Question: Where is a good place to keep track of where the files came from? I downloaded these from aws s3 us-east-1 with the help of a table provided by PNOC. I merged and renamed fastq files, so what's a good way to store the logic? I could add information to that excel table, but it probably shouldn't be stored on github.

**Comment by melissacline** [comment]
Here's one idea.  Could you encapsulate the commands in a bash script and check it in along with the input file, maybe as CKCC/PNOC_RNA-seq.20160114.10.bash?  This is an awesome question, since try as we might, this probably won't be the last time we have to do special processing for some input set...

**Comment by Jeltje** [comment]
Good idea! I actually ran a bunch of python script on a mesos box, but I'll check in a directory with relevant scripts, and, more importantly: notes on pitfalls...

**Comment by melissacline** [comment]
When it's time to run the pipelines on these data, let's go with John's new pipelines against GRCh38.  I've received a request to get these added to the big recompute, and once the recompute is done, no one will be interested in GRCh37 results.  I'm checking with John on whether or not he'll run them himself as part of the big recompute, once the data is all nicely packaged.

**Comment by Jeltje** [comment]
Oh man, and I finally have it working!

They're on S3, all ready to go.

**Comment by melissacline** [comment]
Analyzed by John as part of the Big Recompute
