### ISSUE TITLE
Coach Justin Krupp on setup and Travis CI and setup project plan

### ISSUE THREAD

**Issue by wshands** [BD2KGenomics/core-operations#108]
Get Justin up to speed on Docker, dcc- repos, Travis CI, Github
Have him implement Travis CI for dcc- repos
As a user, I would Travis CI tests run on my programs when I submit a pull request

Tasks

 - [ x ] Enable Travis CI infrastructure to run Fusion pipeline #118
 - [x  ] Create pull request to dcc-action-service

**Comment by wshands** [comment]
https://ucsc-cgl.atlassian.net/wiki/spaces/DIS/pages/edit/141689020?draftId=141689031&draftShareId=f9c010a1-d370-4e4e-acd0-b8471adc0e3e&

**Comment by cricketsloan** [comment]
I think this is resolved.  Future tickets will be in platform-administration
