### ISSUE TITLE
Get permission to redistribute expression counts for FLX Bio samples

### ISSUE THREAD

**Issue by wshands** [BD2KGenomics/core-operations#110]
Need to email authors of studies from which FLX Bio wants samples processed
parent is #150

**Comment by wshands** [comment]
Authors have been sent emails; getting responses

**Comment by wshands** [comment]
Responses recorded here: https://ucsc-cgl.atlassian.net/wiki/spaces/DEV/pages/140476445/Data+sets+to+process+for+FLX+Bio

**Comment by wshands** [comment]
BluePrint: Yes
ICGC PCAWG: embargo policy in place until main paper published

**Comment by kozbo** [comment]
closing as this is not something that we can do
