### ISSUE TITLE
Validate that invoicing/pricing works

### ISSUE THREAD

**Issue by kozbo** [BD2KGenomics/core-operations#112]
Tally up the costs for all jobs run for October using our new invoicing code. Then see if correlates to our actual bill from Amazon for that month.

**Comment by wshands** [comment]
I see a possible bug where storage costs for August 2017 are missing

**Comment by wshands** [comment]
Also need to sort costs by year then month so 2016 data is not interspersed in 2017 data

**Comment by caaespin** [comment]
@wshands  I got sucked into HCA again. Can you guys work on this ticket? Ping me if you guys have questions.  I would probably open another ticket to fix the duplicates bug

**Comment by kozbo** [comment]
closing because we will not be running aa service for treehouse
