### ISSUE TITLE
Work with Alissa at Broad to put annotation and analysis pipelines in Dockstore

### ISSUE THREAD

**Issue by wshands** [BD2KGenomics/core-operations#134]
Work with Alisa Manning at the Broad to put annotation pipeline in Dockstore

[x] - email and call to establish initial work to be done
[x] - establish connection with Alisa's team; Tim Majarian
[ ] - work with Tim Majarian to put analysis workflow into Dockstore

**Comment by cricketsloan** [comment]
moved to https://github.com/BD2KGenomics/platform-administration/issues/19
