### ISSUE TITLE
write pipeline as leader autoscaling document

### ISSUE THREAD

**Issue by wshands** [BD2KGenomics/core-operations#147]
Write a document that describes the requirements for making the Toil leader the same as the running pipeline. An example of this is the latest commit to the Toil RNA-Seq pipeline. 
https://github.com/BD2KGenomics/toil-rnaseq/commit/a32acc335aa3f00b38a6dfe0e63c1d25e57cead0

https://github.com/BD2KGenomics/toil-rnaseq/pull/139

**Comment by cricketsloan** [comment]
moved to: https://github.com/BD2KGenomics/platform-administration/issues/21
