### ISSUE TITLE
Update bucket policies and SOPs

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/core-operations#16]
I've updated the bucket policy examples. This was necessary to fix the problem that @Jeltje ran into when copying the data out of the Stanford inbox into the final bucket.

https://gist.github.com/hannes-ucsc/b0a7ba99d3fd6fcb09bf/revisions
https://gist.github.com/hannes-ucsc/b04d3f349bc73dcca0b5/revisions

Those changes need to be applied to the existing buckets and the SOPs.

**Comment by melissacline** [comment]
Done!
