### ISSUE TITLE
Validate toil-scripts 1.0 release

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/core-operations#25]
Run one sample per pipeline.

If a incoming production batch exercises a pipeline in the next few days, that's fine too.

**Comment by briandoconnor** [comment]
@Jeltje and @dyollluap Melissa and I created the following page to indicate you've tested each of the 1.0 workflows.

https://ucsc-cgl.atlassian.net/wiki/display/PROD/Workflow+Acceptance+Testing
