### ISSUE TITLE
ISPY/ Recompute

### ISSUE THREAD

**Issue by briandoconnor** [BD2KGenomics/core-operations#29]
@jvivian and @melissacline I have notes from the planning meeting that John has about 90 samples to recompute for ISPY.  And is waiting for ~70 additional

Can you clarify in this ticket?  Also, if this is duplicate can you close it?

Thanks

**Comment by melissacline** [comment]
we have all of the ISPY data we're expecting.  John has run some of them, and has come across a strange RSEM issue with others.

**Comment by melissacline** [comment]
The RSEM issue has been resolved.  It was my fault.  I'd like to recompute the whole batch just to be safe.  At the moment, the data's getting packaged up neatly...

**Comment by melissacline** [comment]
The input data is on pod at /pod/home/cline/projects/ispy2/data/raw/T0/fastq/ and /pod/home/cline/projects/ispy2/data/raw/T1/fastq/.  The T0 directory contains a larger number of samples at Timepoint 0, while the T1 directory contains a smaller number of samples from some of the same patients at Timepoint 1.  All samples are named uniquely (i.e. there are no naming collisions between Timepoints 0 and 1).  Each directory contains one subdirectory per sample, each containing one pair of gzipped fastqs.

**Comment by jvivian** [comment]
@melissacline — Could this possibly be assigned as a production run? I'm stretched a bit thin at the moment and @benedictpaten relayed to me that the original 100 samples I computed on OpenStack fulfills requirements for the paper.  If there's an issue with this just let me know and I'll try and fit it in.

**Comment by Jeltje** [comment]
@jvivian @melissacline I think that was the plan - I am waiting for Melissa to create a (correctly named) emtpy input file and assign the ticket to me.

**Comment by jvivian** [comment]
@Jeltje Awesome, thank you!

**Comment by melissacline** [comment]
And FWIW, it looks like the data won't be ready until Monday.

**Comment by melissacline** [comment]
@Jeltje , the data should be ready to go now.  The starting input file is checked into github in https://github.com/BD2KGenomics/core-operations/blob/master/ISPY2/ispy2.20160602.29.input.txt.

**Comment by Jeltje** [comment]
Tarring files for upload to S3 (takes a while!)

**Comment by Jeltje** [comment]
Uploaded files; started 30 node cluster tagged with KEY=PROD, PURPOSE=ISPY2; started run

**Comment by Jeltje** [comment]
Amazon terminates the clusters because the spod bid is too low. Figuring out best course of action

**Comment by Jeltje** [comment]
Restarted run on r3.8xlarge instances. Will keep monitoring.

**Comment by Jeltje** [comment]
164 of 166 finished. T0-Sample_916 and  T1-Sample_24205-2 appear to have been truncated during tarring on our end, so redoing those two.

**Comment by melissacline** [comment]
That's great!

**Comment by Jeltje** [comment]
Corrected samples and restarted run.

**Comment by Jeltje** [comment]
Kept getting drive full errors from one of the workers (a remnant of the previous run) and upon terminating that, the rest of the run crashed a little while later (not sure if related, not in mood to find out). Terminated cluster, started afresh.

**Comment by Jeltje** [comment]
T0-Sample_916 finished but the R1 and R2 fastq files of T1-Sample_24205-2 do not have the same line count: 
```
 75026121 T1-Sample_24205-2_R1.fastq.gz
180092324 T1-Sample_24205-2_R2.fastq.gz
```

**Comment by briandoconnor** [comment]
Down to 1 single sample where the fastq were uneven size... @melissacline will reach back out to get replacements

**Comment by melissacline** [comment]
The fastq for the straggler has been rebuilt, and is ready as https://github.com/BD2KGenomics/core-operations/issues/46.  The remaining data has been delivered to Denise Wolf.
