### ISSUE TITLE
Test data load CKCC and Dream Team into storage system

### ISSUE THREAD

**Issue by briandoconnor** [BD2KGenomics/core-operations#33]

**Comment by briandoconnor** [comment]
@benjaminran we've slipped on this a bit and are running behind.  Ping Melissa/Jeltje/Paul to get some URLs for a couple donors worth of sample data in the mean time

**Comment by briandoconnor** [comment]
@benjaminran I'm assigning to you since this is the first thing to do once you show you can write data to S3

**Comment by melissacline** [comment]
@benjaminran , once you're ready for test data, ping @Jeltje for some URLs.

**Comment by cricketsloan** [comment]
This ticket is 2 years old
