### ISSUE TITLE
USC/CTC.Stage2And3.rnaseq.20160323.23.input.txt

### ISSUE THREAD

**Issue by briandoconnor** [BD2KGenomics/core-operations#43]
A placeholder for line 7:

https://docs.google.com/spreadsheets/d/1vTQJzJrcZ4ekU-2Fo5h8IqdbNy2YB-WylS47TtTVFTU/edit?usp=sharing

Details TBD by @melissacline (and ticket name changed, click edit).

RNASeq with 39 samples.

Requested return time 1 month

**Comment by melissacline** [comment]
Waiting on MSC for file transfer from secure FTP

**Comment by briandoconnor** [comment]
@melissacline Alex has asked for her to copy data from SFTP server.  will look at this today or tomorow.

**Comment by briandoconnor** [comment]
main cohort is done as of 6/13/2016... a few had issues... this past week got them transferred over.  These aren't ready to run yet but @melissacline is working on them.  So maybe in the next couple days should be ready for Jeltje.

**Comment by melissacline** [comment]
The remaining samples are being run under https://github.com/BD2KGenomics/core-operations/issues/47.

**Comment by briandoconnor** [comment]
See update by @melissacline on #47

**Comment by melissacline** [comment]
Three remaining stragglers being run as https://github.com/BD2KGenomics/core-operations/issues/48.
