### ISSUE TITLE
WCDT/<pending>

### ISSUE THREAD

**Issue by briandoconnor** [BD2KGenomics/core-operations#45]
See line 5 of the order sheet

**Comment by briandoconnor** [comment]
Don't have the data yet, waiting from Robert.

**Comment by briandoconnor** [comment]
@melissacline reports don't have the data yet, waiting from Robert. She ping'd earlier this week.

**Comment by melissacline** [comment]
Melissa emailed Robert, Ted, and Laura Heiser today (06/16/16) to indicate that in absence of a respose, I'm assuming that these data are not yet available or have been analyzed elsewhere, and I'm closing this request.

**Comment by melissacline** [comment]
Robert indicates that this is the batch that John ran last fall (https://github.com/BD2KGenomics/core-operations/issues/2)
