### ISSUE TITLE
Copy the files from Batch 51 to pod

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/core-operations#54]
From Ann Durbin:

Holly has asked me to ask you for this - although this may not be the way for this to happen in the future. If there's a way for us to do this, will you let us know?

She would like both the files and the manifest of the FASTQ input files for the recent Stanford set Q1-Q10. We think this was processed as Batch 51. She will use the manifest to match fastq files to bam output files. 

 May we ask that the fastq files be copied to /pod/pstore/groups/treehouse/backed_up/Stanford/RNA-Seq/fastq ?

(to clarify, the files in question are the input fastq files or tarballs, and the manifest is the file used to launch the workflow).

**Comment by Jeltje** [comment]
Done!
Copied everything, including the 'Menifest' file that came with the samples, and the md5sums.

The manifest file for the workflow is called rnaseq-config.txt - it's also in /pod/pstore/groups/treehouse/backed_up/Stanford/RNA-Seq/fastq
