### ISSUE TITLE
Generate a bundle of sample FASTQC reports for Ilian

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/core-operations#55]

**Comment by melissacline** [comment]
The first batch of CHOC samples are the questionable ones.  That's Batch #40, and here are the sample IDs:
AH07020812_ACACGA
AO20062212_GTGGCC
BV18060612_CACCTC
CV11030912_CACACA
JA10030112_GTGTTA
JP21062512_TGTTGC
KC23072512_AAGGGA
KS08021312_TGTGAA
NK09031127_ACAAAC
So, let's take those and a dozen or so random other samples (we're assuming that these dozen or so samples are of decent quality).

**Comment by kozbo** [comment]
What is the disposition of this issue?
