### ISSUE TITLE
UCSF RNA-seq medbook Batch9/DTB-100,DTB-108

### ISSUE THREAD

**Issue by dyollluap** [BD2KGenomics/core-operations#7]
Reprocessing 2 RNA-seq samples from UCSF batch 9:
DTB-100_Baseline
DTB-108_Baseline
Previous .zip files on podk were corrupted, produced corrupted fastq. 
New .tar uploaded direct from UCSF BaseSpace 20151222 to medbook FTP.
Processing with BD2K UNC RNA-seq pipeline.

**Comment by melissacline** [comment]
Awesome!

Paul, while you're at it, would you set up the issue for the Target
RNASeq?  You can use thengithub issue mover to move the issue from
driver-projects.

Thanks!
Elissa
