### ISSUE TITLE
Move CKCC files for Batches 14 and 21 from S3

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/core-operations#70]
Hi Ann, 

Sure - I can download files quickly if you have the S3 and output locations. 
I don't have time to do any actual thinking today, so if it takes sleuthing, it will have to wait until tomorrow...

CCing Brian because he wants to keep abreast of the amount of data we download on your behalf - it costs the core money to move things off S3.

Best, 
-Jeltje

On Wed, Jul 27, 2016 at 12:04 PM, Ann Durbin <adurbin@ucsc.edu> wrote:
Hi Jeltje,
I didn't know whether to make this a Core issue (since it isn't about processing). Would you be able to download any of our CKCC DNA files from S3 to the appropriateTreehouse directories? I think this would be samples from batch 14 and batch 21 only, but please let me know if you are aware of any others. 

This is for an analysis Holly is hoping to start right away. 

Thanks very much,
Ann

-- 
Ann Durbin
CKCC Data Coordinator
Genomics Institute, UCSC

**Comment by adurbin2** [comment]
Thanks Melissa! Just changing the title to reflect only batch 21 files --

**Comment by adurbin2** [comment]
I think they belong here:
/pod/pstore/groups/treehouse/backed_up/PNOC/DNA/WES

- there are six files there already from the other batch. Thanks -

**Comment by Jeltje** [comment]
@adurbin2 let me know where you want them on pstore and we're in business!

**Comment by Jeltje** [comment]
We lost stacker, and I can't seem to run pip on podk, which means that I can't install the s3am or the awscli download program. Investigating...

**Comment by Jeltje** [comment]
Holly found a solution for creatng a virtual environment. Started download.

**Comment by Jeltje** [comment]
Download still running, 75 of 84 files retrieved.

**Comment by Jeltje** [comment]
Done
