### ISSUE TITLE
Copy 27 CKCC files from S3 to Pod.71

### ISSUE THREAD

**Issue by adurbin2** [BD2KGenomics/core-operations#71]
@Jeltje Would you kindly copy (not move) these 27 RNASeq files sent by Stanford on July 14th? They are awaiting processing as part of Batch 68. The copies should be placed in /pod/pstore/groups/treehouse/backed_up/Stanford/RNA-Seq/fastq/

Here's the list of 27 samples:
M10-PSS050 RNASeq
M11-PSS077 RNASeq
M12-PSS077_patient  RNASeq
M3-PSS031 RNASeq
M4-PSS031patient  RNASeq
M5-PSS031cellline  RNASeq
M6-PSS113 RNASeq
M7-PSS113patient  RNASeq
M8-PSS008 RNASeq
M9-PSS008patient  RNASeq
N10-PSS085x1mm1  RNASeq
N11-PSS089 RNASeq
N4-PSS119 RNASeq
N5-PSS119patient  RNASeq
N6-PSS131 RNASeq
N7-PSS112 RNASeq
N8-PSS085 RNASeq
O3-PSS004 RNASeq
O4-PSS004cellline  RNASeq
O5-PSS091A RNASeq
O6-PSS091Apatient  RNASeq
P4-PSS012 RNASeq
P5-PSS012patient  RNASeq
P6-PSS012cellline  RNASeq
P7-PSS018 RNASeq
P8-PSS141 RNASeq
P9-PSS078 RNASeq

**Comment by adurbin2** [comment]
changing issue to #71

**Comment by Jeltje** [comment]
Started download

**Comment by Jeltje** [comment]
Finished
