### ISSUE TITLE
Download issue73 samples to pod

### ISSUE THREAD

**Issue by adurbin2** [BD2KGenomics/core-operations#74]
Hi @Jeltje - Can you please download the files (tar and md5) found at AWS in cgk-inbox-ckcc-stanford to the Treehouse folder 
http://stacker.pod/pod/pstore/groups/treehouse/backed_up/Stanford/RNA-Seq/fastq  ?

The files are 
https://cgl-inbox-ckcc-stanford.s3.amazonaws.com/Menifest.txt
https://cgl-inbox-ckcc-stanford.s3.amazonaws.com/R1_436-14.tar
https://cgl-inbox-ckcc-stanford.s3.amazonaws.com/R1_436-14.tar.md5
https://cgl-inbox-ckcc-stanford.s3.amazonaws.com/R2_499-5.tar
https://cgl-inbox-ckcc-stanford.s3.amazonaws.com/R2_499-5.tar.md5
https://cgl-inbox-ckcc-stanford.s3.amazonaws.com/R3_308-7.tar
https://cgl-inbox-ckcc-stanford.s3.amazonaws.com/R3_308-7.tar.md5
https://cgl-inbox-ckcc-stanford.s3.amazonaws.com/R4_010-33.tar
https://cgl-inbox-ckcc-stanford.s3.amazonaws.com/R4_010-33.tar.md5
https://cgl-inbox-ckcc-stanford.s3.amazonaws.com/R5_425-6.tar
https://cgl-inbox-ckcc-stanford.s3.amazonaws.com/R5_425-6.tar.md5
https://cgl-inbox-ckcc-stanford.s3.amazonaws.com/R6_497-6T.tar
https://cgl-inbox-ckcc-stanford.s3.amazonaws.com/R6_497-6T.tar.md5
https://cgl-inbox-ckcc-stanford.s3.amazonaws.com/R7_367-16.tar
https://cgl-inbox-ckcc-stanford.s3.amazonaws.com/R7_367-16.tar.md5
https://cgl-inbox-ckcc-stanford.s3.amazonaws.com/R8_010-31.tar
https://cgl-inbox-ckcc-stanford.s3.amazonaws.com/R8_010-31.tar.md5
https://cgl-inbox-ckcc-stanford.s3.amazonaws.com/R9_492-6.tar
https://cgl-inbox-ckcc-stanford.s3.amazonaws.com/R9_492-6.tar.md5
https://cgl-inbox-ckcc-stanford.s3.amazonaws.com/R10_496-6.tar
https://cgl-inbox-ckcc-stanford.s3.amazonaws.com/R10_496-6.tar.md5
https://cgl-inbox-ckcc-stanford.s3.amazonaws.com/R11_298-9.tar
https://cgl-inbox-ckcc-stanford.s3.amazonaws.com/R11_298-9.tar.md5
https://cgl-inbox-ckcc-stanford.s3.amazonaws.com/R12_456-3.tar
https://cgl-inbox-ckcc-stanford.s3.amazonaws.com/R12_456-3.tar.md5

Is "data load" an appropriate GitHub label for this? I was guessing...
Thanks,
Ann

**Comment by Jeltje** [comment]
Done. Menifest.txt already existed, so downloaded as Menifest_20160829.txt
