### ISSUE TITLE
WCDT 3 patient samples for rnaseq-unc

### ISSUE THREAD

**Issue by chkw** [BD2KGenomics/core-operations#92]
# Overview

This is a Github ticket to track an analysis batch submitted to the core.  Basic information for this request:

* PROJECT NAME - WCDT Prostate Cancer
* DATE REQUESTED - December 02, 2016
* CLOUD SHEPHERD
* DATE DATA UPLOADED AND AVAILABLE
* DATE ANALYSIS STARTED
* DATE ANALYSIS COMPLETE

Feel free to add these sections as distinct comments to the ticket so you can add them over time.

# Workflow & Version

Indidate the workflow and version used along with how it was run (pip install, Docker, single-node, multi-node, on AWS, etc)

3 patient samples to be processed with rnaseq-unc expression pipeline. The unc pipeline is being requested in order to match the processing of the samples already run through rnaseq-unc.

# Input Manifest

Please attach the input manifest that shows the S3 URLs for the input files.

The rnaseq data files are at:
https://s3-us-west-2.amazonaws.com/ucsf-rnaseq-su2c/fastq/DTB-060_Progression.tar
https://s3-us-west-2.amazonaws.com/ucsf-rnaseq-su2c/fastq/DTB-022_Progression.tar
https://s3-us-west-2.amazonaws.com/ucsf-rnaseq-su2c/fastq/DTB-135_Baseline.tar

The s3am encryption key is at [box](https://ucsf.box.com/s/r5mj1ivrhxborc8x6tnzrh1kdx5dv1d2)

# Workflow Configuration

Please attach the workflow configuration file used.

# Output Manifest

Please attach a list of URLs (typically S3 URLs) that can be shared with the primary contact.

# Cleanup

Please indicate if the inputs and/or outputs were deleted from S3.

# Additional Notes

**Comment by wshands** [comment]
RNA-Seq UNC was run on the samples and results are at cgl-driver-projects-encrypted/wcdt/WCDT3RNASeqoutput2016_12_07/

**Comment by Jeltje** [comment]
@wshands  Can you output to cgl-driver-projects instead? We try to keep input and output separated by keeping them in different buckets -cgl-driver-projects-encrypted is for input (of course they're both encrypted now, but that used to be different)

**Comment by wshands** [comment]
OK yes I can do that in the future

**Comment by cricketsloan** [comment]
This issue is closed
