### ISSUE TITLE
EGAD00001001098 Missing one file

### ISSUE THREAD

**Issue by rcurrie** [BD2KGenomics/core-operations#94]
Center: EGAD00001001098
Program: Treehouse
Project: Compendium

Manifest included 63 sets  samples, each comprising two pairs of paired reads and therefore should have resulted in 4 * 63 = 252 files. File browser shows 251 so one went missing somewhere.

**Comment by wshands** [comment]
File browser now shows 252 fastq.gz files for Compendium
