### ISSUE TITLE
Collect samples for Stanford-PDX-RNASeq-2017Feb14

### ISSUE THREAD

**Issue by adurbin2** [BD2KGenomics/core-operations#95]
Hi @Jeltje , 
Treehouse has incoming Stanford samples. I'm sorry to trouble you, and I expect this will be the last time... we're working on Girder as a way to gather partner samples from future batches. However, we have just now received these five, and they're urgently needed for an analysis Olena is doing this week. Would you be so kind as to decrypt/download them to pod?  Thanking you in advance...

Here is a good folder to put them in:
sftp://stacker.pod/pod/pstore/groups/treehouse/backed_up/Stanford/RNA-Seq/fastq

and here are the files (just these; there are others in the bucket that we do not need):

https://cgl-inbox-ckcc-stanford.s3.amazonaws.com/O7.tar
https://cgl-inbox-ckcc-stanford.s3.amazonaws.com/O7.tar.md5
https://cgl-inbox-ckcc-stanford.s3.amazonaws.com/O8.tar
https://cgl-inbox-ckcc-stanford.s3.amazonaws.com/O8.tar.md5
https://cgl-inbox-ckcc-stanford.s3.amazonaws.com/P10.tar
https://cgl-inbox-ckcc-stanford.s3.amazonaws.com/P10.tar.md5
https://cgl-inbox-ckcc-stanford.s3.amazonaws.com/P11.tar
https://cgl-inbox-ckcc-stanford.s3.amazonaws.com/P11.tar.md5
https://cgl-inbox-ckcc-stanford.s3.amazonaws.com/P12.tar
https://cgl-inbox-ckcc-stanford.s3.amazonaws.com/P12.tar.md5

**Comment by Jeltje** [comment]
Done.
