### ISSUE TITLE
Request download to pod

### ISSUE THREAD

**Issue by adurbin2** [BD2KGenomics/core-operations#96]
Hi @Jeltje,

Once again, we are asking you to download and decrypt a set of four RNASeq samples from Stanford to the Treehouse directory. The files we want to download are U12, U15, U16, and U17. These are samples urgently needed for an analysis Olena is working on. If all goes well, we shouldn't need to ask you for this assistance again :)

Files are here: https://s3.amazonaws.com/cgl-inbox-ckcc-stanford

Please download the files to: sftp://stacker.pod/pod/pstore/groups/treehouse/backed_up/archive/input/fastq

Thanks very much -

**Comment by Jeltje** [comment]
@adurbin2 Done. 
Please verify that they are OK and I will empty the inbox.

**Comment by adurbin2** [comment]
@Jeltje  Yes - they are fine, and thank you for emptying the inbox!

**Comment by Jeltje** [comment]
Done
